version: "3.8"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openmrs
      MYSQL_USER: openmrs
      MYSQL_PASSWORD: openmrs
    ports:
      - "3306:3306"
    volumes:
      - openmrs-db:/var/lib/mysql

  app:
    build: .
    depends_on: [db]
    ports:
      - "8080:8080"
    environment:
      OPENMRS_DB_HOST: db
      OPENMRS_DB_NAME: openmrs
      OPENMRS_DB_USERNAME: openmrs
      OPENMRS_DB_PASSWORD: openmrs

volumes:
  openmrs-db:
